name: Selenium Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Chrome v123 & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxss1 libappindicator3-1 libindicator7 fonts-liberation libnss3 lsb-release xdg-utils

          # Instalar Chrome v123
          wget https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.86/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome

          # Eliminar enlace simbólico si ya existe
          if [ -L /usr/bin/google-chrome ]; then
            sudo rm /usr/bin/google-chrome
          fi

          # Crear nuevo enlace simbólico
          sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome

          # Instalar ChromeDriver correspondiente
          wget https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.86/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

          # Verificar versiones
          google-chrome --version
          chromedriver --version

      - name: Run tests
        run: |
          xvfb-run python -m test.TestReportes
